services:
  mono:
    container_name: turret-mono
    network_mode: host

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      NODE_ENV: development

    volumes:
      - ./:/app

    command: pnpm dev
    working_dir: /app
